spring:
  datasource:
    url: jdbc:mysql://${hostname}:3306/bonus?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username:
    password:

mybatis:
  type-aliases-package: com.huilianjk.bonus.pojo
  config-location: classpath:mybatis.xml
